version: '3.7'
services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_DB: 'oblik_db'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'oblik_user'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'oblik_pass'

      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      # <Port exposed> : < Postgres port running inside container>
      - '5432:5432'
    expose:
      # Opens port 5432 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - postgresdata:/var/lib/postgresql/data/pgdata
      - postgrestbs:/var/opt/postgres/tablespaces
      - postgreslogs:/var/log
# Names our volume
volumes:
  postgresdata:
  postgrestbs:
  postgreslogs: