oblik.security:
  tokenHeader: Bearer
  secret: abcdes # secret to sign the token
  expiration: 86400

logging:
  file: oblik.log
  level:
    org.ua.oblik: DEBUG
    org.springframework: INFO

server:
  context-path: "/oblik-api"
  port: 8090

flyway:
  locations: "classpath:db/mysql"
  baseline-on-migrate: true
