oblik.security:
  tokenHeader: Bearer
  secret: abcdes # secret to sign the token
  expiration: 86400

logging:
  file: oblik.log
  level:
    org.ua.oblik: DEBUG
    org.springframework: INFO

server:
  servlet.context-path: "/oblik-api"
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:h2:mem:oblik
    username: sa
    password:

  flyway:
    baseline-on-migrate: true
    locations: classpath:/db/migration/{vendor}

  jpa:
    show-sql: true
